### ISSUE TITLE
Keepkey library no longer loaded in 5.0.3

### ISSUE THREAD

**Issue by jasonbcox** [Bitcoin-ABC/ElectrumABC#158]
I get this message when opening a wallet file tied to a keepkey:
```
Cannot find python library for 'keepkey'.
Make sure you install it with python3
```

Confirmed it works in 5.0.2. I'm using the AppImage, if it matters.

**Comment by PiRK** [comment]
Some additional troubleshooting info: 
I created a wallet file using an existing ledger wallet, set `"hw_type": "keepkey"`

I build an AppImage using the regular  (non-detersministic) requirements-*.txt files, after applying the following patch:

```
--- a/electroncash_plugins/keepkey/keepkey.py
+++ b/electroncash_plugins/keepkey/keepkey.py
@@ -82,7 +82,8 @@ class KeepKeyPlugin(HW_PluginBase):
     def __init__(self, parent, config, name):
         HW_PluginBase.__init__(self, parent, config, name)
 
-        try:
+        # try:
+        if True:
             from electroncash_plugins.keepkey import client
             import keepkeylib
             import keepkeylib.ckd_public
@@ -99,8 +100,8 @@ class KeepKeyPlugin(HW_PluginBase):
             self.usb_context = USBContext()
             self.usb_context.open()
             self.libraries_available = True
-        except ImportError:
-            self.libraries_available = False
+        # except ImportError:
+        #     self.libraries_available = False
 
     def libusb_enumerate(self):
         from keepkeylib.transport_webusb import DEVICE_IDS
```

The error message when loading the wallet is:
```
ImportError('/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/hid.cpython-38-x86_64-linux-gnu.so: Commande de chargement sur une adresse ELF incorrectement alignée')
Traceback (most recent call last):
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash_gui/qt/__init__.py", line 623, in start_new_window
    raise e
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash_gui/qt/__init__.py", line 617, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/daemon.py", line 281, in load_wallet
    wallet = Wallet(storage)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/wallet.py", line 3283, in __new__
    wallet = WalletClass(storage)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/wallet.py", line 3119, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/wallet.py", line 2995, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/wallet.py", line 271, in __init__
    self.load_keystore_wrapper()
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/wallet.py", line 322, in load_keystore_wrapper
    self.load_keystore()
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/wallet.py", line 3127, in load_keystore
    self.keystore = load_keystore(self.storage, 'keystore')
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/keystore.py", line 705, in load_keystore
    k = hardware_keystore(d)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/keystore.py", line 689, in hardware_keystore
    return constructor(d)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/plugins.py", line 471, in dynamic_constructor
    plugin = self.get_internal_plugin(name, force_load=True)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/plugins.py", line 198, in get_internal_plugin
    self.load_internal_plugin(name)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash/plugins.py", line 222, in load_internal_plugin
    plugin = p.Plugin(self, self.config, name)
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/electroncash_plugins/keepkey/keepkey.py", line 90, in __init__
    import keepkeylib.transport_hid
  File "/tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/keepkeylib/transport_hid.py", line 9, in <module>
    import hid
ImportError: /tmp/.mount_Electrm2rIDE/usr/lib/python3.8/site-packages/hid.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

**Comment by PiRK** [comment]
It could be caused by the [removal of `:no-binary:`in the `pip install` commands](https://github.com/Bitcoin-ABC/ElectrumABC/pull/151/commits/8b6cc9334690a52750d4518f23be7b08c478447b#diff-b5ef81ead69055edb978fccd9f6f8ffc351fb795844c596ff4584b1a4bd7b7beL115). Maybe the build process grabbed one of the python libraries in a compiled form (python wheel) instead of compiling it, and that binary library does not work with this version of python. 
I don't know much about compilation, but I have seen similar issues in the past, after python upgraded their compilation  chain.

**Comment by PiRK** [comment]
I'm building a new AppImage for you to test, after fixing the build script using  `pip install :no-binary: ...`  via #159.
For me, it is working. I can now load my fake KeepKey wallet without an error.

**Comment by PiRK** [comment]
Can you try the AppImage in the artifacts of that build: https://cirrus-ci.com/task/5768592114319360

**Comment by jasonbcox** [comment]
This appears to work. Thank you.
