### ISSUE TITLE
AttributeError: 'Standard_Wallet' object has no attribute 'start_network'

### ISSUE THREAD

**Issue by PiRK** [Bitcoin-ABC/ElectrumABC#163]
# Description
Creating  a new wallet from a trezor device, just after the "set wallet file encryption" wizard page, no matter if the checkbox is checked or unchecked.

This happened  while testing #162 (probably does not affect master).
# Traceback
```
Traceback (most recent call last):
  File "electroncash_gui\qt\main_window.py", line 661, in new_wallet
  File "electroncash_gui\qt\__init__.py", line 622, in start_new_window
  File "electroncash_gui\qt\__init__.py", line 682, in _start_wizard_to_select_or_create_wallet
AttributeError: 'Standard_Wallet' object has no attribute 'start_network'

```

# System information

- Electrum ABC version: 5.0.3
- Python version: 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
- Operating system: Windows-10-10.0.19041-SP0
- Wallet type: standard
- Locale: fr_FR

**Comment by PiRK** [comment]
fixed with a force-push to #162. It was a backport error, our codebase has a `start_threads` method instead of a `start_network` method.
