### ISSUE TITLE
Error when trying to read QR code from camera

### ISSUE THREAD

**Issue by PiRK** [Bitcoin-ABC/ElectrumABC#178]
This happens when trying to read QR code from camera using the AppImage for 5.0.4
```
Traceback (most recent call last):
  File "/tmp/.mount_ElectrLEEsCq/usr/lib/python3.8/site-packages/electroncash_gui/qt/qrtextedit.py", line 149, in qr_input
    self.qr_dialog = QrReaderCameraDialog(parent=self.top_level_window())
  File "/tmp/.mount_ElectrLEEsCq/usr/lib/python3.8/site-packages/electroncash_gui/qt/qrreader/camera_dialog.py", line 153, in __init__
    self.image_effect = ImageGraphicsEffect(self, self.crop_blur_effect)
  File "/tmp/.mount_ElectrLEEsCq/usr/lib/python3.8/site-packages/electroncash_gui/qt/utils/image_effect.py", line 42, in __init__
    self.graphics_item.setGraphicsEffect(effect)
AttributeError: 'QGraphicsScene' object has no attribute 'setGraphicsEffect'
```

**Comment by PiRK** [comment]
Electron Cash 4.2.6 does not have this issue.
