### ISSUE TITLE
TypeError: disconnect() failed between 'textChanged' and all its connections

### ISSUE THREAD

**Issue by jwagoner88** [Bitcoin-ABC/ElectrumABC#180]
# Description

# Traceback
```
Traceback (most recent call last):
  File "C:\Users\17193\AppData\Roaming\ElectrumABC\external_plugins\AutoCove-Plugin.zip\AutoCove\qt.py", line 663, in AsmBoxHighlighted
    def AsmBoxHighlighted(self,Index): self.AsmBox.setCurrentIndex(Index), self.AsmBoxActivated()   #Highlighted → Activated.
  File "C:\Users\17193\AppData\Roaming\ElectrumABC\external_plugins\AutoCove-Plugin.zip\AutoCove\qt.py", line 671, in AsmBoxActivated
    self.ColorsBox.setChecked(False), self.AsmBoxHighlighted(0), self.AsmBox.setCurrentIndex(Index), self.ColorsBox.setChecked(ColorsBool)
  File "C:\Users\17193\AppData\Roaming\ElectrumABC\external_plugins\AutoCove-Plugin.zip\AutoCove\qt.py", line 663, in AsmBoxHighlighted
    def AsmBoxHighlighted(self,Index): self.AsmBox.setCurrentIndex(Index), self.AsmBoxActivated()   #Highlighted → Activated.
  File "C:\Users\17193\AppData\Roaming\ElectrumABC\external_plugins\AutoCove-Plugin.zip\AutoCove\qt.py", line 672, in AsmBoxActivated
    self.ScriptBox.textChanged.disconnect(), self.ScriptBox.selectionChanged.disconnect()
TypeError: disconnect() failed between 'textChanged' and all its connections

```

# System information

- Electrum ABC version: 5.0.4
- Python version: 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
- Operating system: Windows-10-10.0.19041-SP0
- Wallet type: standard
- Locale: en_US

**Comment by PiRK** [comment]
Hi, Thanks for reporting the issue. 

I opened an issue to  the plugin repository : https://github.com/TinosNitso/AutoCove-Plugin/issues/2

If it prevents you from using Electrum ABC, the immediate fix is to disable / uninstall the external plugin.
If you can share some more context on what happened, what you were trying to do... it would be helpful.
