### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by wasiirka** [Bitcoin-ABC/ElectrumABC#225]
# Description

# Traceback
```
Traceback (most recent call last):
  File "electroncash_gui\qt\consolidate_coins_dialog.py", line 144, in on_page_changed
  File "electroncash_gui\qt\consolidate_coins_dialog.py", line 53, in __init__
  File "electroncash\consolidate.py", line 69, in __init__
AssertionError

```

# System information

- Electrum ABC version: 5.0.4
- Python version: 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
- Operating system: Windows-10-10.0.19041-SP0
- Wallet type: imported_addr,standard
- Locale: en_US

**Comment by wasiirka** [comment]
plz help

**Comment by PiRK** [comment]
The limit already exists, but I think the test is wrong.

**Comment by wasiirka** [comment]
Thanks pirk great man
