### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'c:\\users\\kris636\\appdata\\roaming\\electrumabc\\wallets\\baby636#86037.8835595521🔑\n.tmp.1892'

### ISSUE THREAD

**Issue by baby636** [Bitcoin-ABC/ElectrumABC#242]
# Description

# Traceback
```
Traceback (most recent call last):
  File "electroncash_gui\qt\main_window.py", line 675, in new_wallet
  File "electroncash_gui\qt\__init__.py", line 623, in start_new_window
  File "electroncash_gui\qt\__init__.py", line 667, in _start_wizard_to_select_or_create_wallet
  File "electroncash\base_wizard.py", line 591, in create_storage
  File "electroncash\util.py", line 372, in &lt;lambda&gt;
  File "electroncash\util.py", line 368, in do_profile
  File "electroncash\storage.py", line 86, in write
  File "electroncash\storage.py", line 98, in _write
OSError: [Errno 22] Invalid argument: 'c:\\users\\kris636\\appdata\\roaming\\electrumabc\\wallets\\baby636#86037.8835595521🔑\n.tmp.1892'

```

# System information

- Electrum ABC version: 5.1.5
- Python version: 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
- Operating system: Windows-10-10.0.22000-SP0
- Wallet type: standard
- Locale: de_DE

**Comment by PiRK** [comment]
Weird. Looks like the ElectrumWindow.new_wallet generated a crazy filename. I will have to figure out how to reproduce this before I can fix it.

Did you somehow change the default wallet path? Or pass a command line argument (-w or --wallet) when starting the program?

**Comment by Saeed149** [comment]
Hi
