### ISSUE TITLE
Problem opening a Ledger on Windows

### ISSUE THREAD

**Issue by PiRK** [Bitcoin-ABC/ElectrumABC#28]
Firmware 1.4.7

Reported issue:

> It says derivation path is not compatible and then it shows some random address in my ledger
The problem happens after selectiing "unamed ledger xxxxxx" . The "Derivation path for standard wallet" is never displayed.

Log  message when run in `--verbose` mode (this is Electron Cash, but the user reports the same problem  for Electrum)
```
| 38.014| |04| [ec-bcn.criptolayer.net] connected chunk, height=661796 count=147 proof_was_provided=True
| 38.308| |00| [Plugins] loaded internal plugin digitalbitbox
| 38.364| |00| [Plugins] loaded internal plugin keepkey
| 38.384| |00| [Plugins] loaded internal plugin ledger
| 38.401| |00| [satochip] init()
| 38.401| |00| [Plugins] loaded internal plugin satochip
| 38.506| |00| [Plugins] loaded internal plugin trezor
| 38.507| |00| [DeviceMgr] scanning devices...
| 38.558| |00| [satochip] detect_smartcard_reader
| 38.560| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (1): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
| 40.674| |00| [DeviceMgr] scanning devices...
| 40.756| |00| [satochip] detect_smartcard_reader
| 40.757| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (9): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
=> b'e0c4000000'
<= b'1b30010407010003'9000
| 96.322| |00| [DeviceMgr] scanning devices...
| 96.377| |00| [satochip] detect_smartcard_reader
| 96.379| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "electroncash\base_wizard.py", line 249, in on_device
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 611, in setup_device
    client.get_xpub("m/44'/0'", 'standard') # TODO replace by direct derivation once Nano S > 1.1
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 47, in catch_exception
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 114, in get_xpub
    nodeData = self.dongleObject.getWalletPublicKey(prevPath)
  File "site-packages\btchip\btchip.py", line 124, in getWalletPublicKey
  File "site-packages\btchip\btchipComm.py", line 127, in exchange
btchip.btchipException.BTChipException: Exception : Invalid status 6985

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (2): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
| 42.842| |00| [DeviceMgr] scanning devices...
| 42.922| |00| [satochip] detect_smartcard_reader
| 42.924| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (3): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
=> b'e0c4000000'
<= b'1b30010407010003'9000
=> b'f026000000'
<= b''6d00
| 45.061| |00| [DeviceMgr] Registering <electroncash_plugins.ledger.ledger.Ledger_Client object at 0x05ADE6B0>
| 45.064| |00| [DeviceMgr] scanning devices...
| 45.146| |00| [satochip] detect_smartcard_reader
| 45.148| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '
INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (10): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
=> b'e0c4000000'
<= b'1b30010407010003'9000
| 98.501| |00| [DeviceMgr] scanning devices...
| 98.581| |00| [satochip] detect_smartcard_reader
| 98.583| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "electroncash\base_wizard.py", line 249, in on_device
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 611, in setup_device
    client.get_xpub("m/44'/0'", 'standard') # TODO replace by direct derivation once Nano S > 1.1
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 47, in catch_exception
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 114, in get_xpub
    nodeData = self.dongleObject.getWalletPublicKey(prevPath)
  File "site-packages\btchip\btchip.py", line 124, in getWalletPublicKey
  File "site-packages\btchip\btchipComm.py", line 127, in exchange
btchip.btchipException.BTChipException: Exception : Invalid status 6985

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (11): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
=> b'e0c4000000'
<= b'1b30010407010003'9000
|111.550| |00| [Daemon] stopping, removing lockfile
|111.551| |00| Removed lockfile: C:\Users\admin\AppData\Roaming\ElectronCash\daemon
|111.594| |16| [Daemon] shutting down network
|111.672| |04| [Network] stopping network
|111.676| |04| [Network] stopped
|111.676| |16| [Daemon] stopped
|111.782| |17| [Plugins] stopped

INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (6): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
=> b'e0c4000000'
<= b'1b30010407010003'9000
=> b'e0c4000000'
<= b'1b30010407010003'9000
=> b'e024000000'
<= b'01'9000
=> b'e02280000130'
<= b''6d00
=> b'e040000005018000002c'
<= b''6985
| 86.919| |00| [InstallWizard] Traceback (most recent call last):
  File "electroncash\base_wizard.py", line 249, in on_device
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 611, in setup_device
    client.get_xpub("m/44'/0'", 'standard') # TODO replace by direct derivation once Nano S > 1.1
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 47, in catch_exception
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 114, in get_xpub
    nodeData = self.dongleObject.getWalletPublicKey(prevPath)
  File "site-packages\btchip\btchip.py", line 124, in getWalletPublicKey
  File "site-packages\btchip\btchipComm.py", line 127, in exchange
btchip.btchipException.BTChipException: Exception : Invalid status 6985

| 89.766| |00| [DeviceMgr] scanning devices...
| 89.814| |00| [satochip] detect_smartcard_reader
| 89.815| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "electroncash\base_wizard.py", line 249, in on_device
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 611, in setup_device
    client.get_xpub("m/44'/0'", 'standard') # TODO replace by direct derivation once Nano S > 1.1
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 47, in catch_exception
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 114, in get_xpub
    nodeData = self.dongleObject.getWalletPublicKey(prevPath)
  File "site-packages\btchip\btchip.py", line 124, in getWalletPublicKey
  File "site-packages\btchip\btchipComm.py", line 127, in exchange
btchip.btchipException.BTChipException: Exception : Invalid status 6985

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (7): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
=> b'e0c4000000'
<= b'1b30010407010003'9000
| 91.931| |00| [DeviceMgr] scanning devices...
| 91.991| |00| [satochip] detect_smartcard_reader
| 91.993| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "electroncash\base_wizard.py", line 249, in on_device
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 611, in setup_device
    client.get_xpub("m/44'/0'", 'standard') # TODO replace by direct derivation once Nano S > 1.1
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 47, in catch_exception
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 114, in get_xpub
    nodeData = self.dongleObject.getWalletPublicKey(prevPath)
  File "site-packages\btchip\btchip.py", line 124, in getWalletPublicKey
  File "site-packages\btchip\btchipComm.py", line 127, in exchange
btchip.btchipException.BTChipException: Exception : Invalid status 6985

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (8): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
=> b'e0c4000000'
<= b'1b30010407010003'9000
| 94.117| |00| [DeviceMgr] scanning devices...
| 94.199| |00| [satochip] detect_smartcard_reader
| 94.201| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "electroncash\base_wizard.py", line 249, in on_device
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 611, in setup_device
    client.get_xpub("m/44'/0'", 'standard') # TODO replace by direct derivation once Nano S > 1.1
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 47, in catch_exception
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\ledger\ledger.py", line 114, in get_xpub
    nodeData = self.dongleObject.getWalletPublicKey(prevPath)
  File "site-packages\btchip\btchip.py", line 124, in getWalletPublicKey
  File "site-packages\btchip\btchipComm.py", line 127, in exchange
btchip.btchipException.BTChipException: Exception : Invalid status 6985

During handling of the above exception, another exception occurred:
INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (4): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
=> b'e0c4000000'
<= b'1b30010407010003'9000
| 47.265| |00| [DeviceMgr] scanning devices...
| 47.347| |00| [satochip] detect_smartcard_reader
| 47.349| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

INFO [init] enumerate_devices | Enumerating UdpTransport: found 0 devices
DEBUG [connectionpool] _new_conn | Starting new HTTP connection (5): 127.0.0.1:21325
INFO [init] enumerate_devices | Enumerating BridgeTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating WebUsbTransport: found 0 devices
INFO [init] enumerate_devices | Enumerating HidTransport: found 0 devices
=> b'e0c4000000'
<= b'1b30010407010003'9000
| 53.221| |00| [DeviceMgr] scanning devices...
| 53.310| |00| [satochip] detect_smartcard_reader
| 53.311| |00| [satochip] Error during connection: EstablishContextException(-2146435043,)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\satochip\satochip.py", line 519, in detect_smartcard_reader
    cardrequest = CardRequest(timeout=0.1, cardType=self.cardtype)
  File "site-packages\smartcard\CardRequest.py", line 61, in init
  File "site-packages\smartcard\pcsc\PCSCCardRequest.py", line 82, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 56, in init
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 70, in renewContext
  File "site-packages\smartcard\pcsc\PCSCContext.py", line 40, in init
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: The Smart Card Resource Manager is not running. '

```
(reported via telegram, messages don't seem to be in the right order)

**Comment by PiRK** [comment]
Upgrading the firmware to 1.6.1 fixed the issue. 
I'm going to close this, as there is a solution that does not require supporting old firmwares (upgrading it).
