### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by baby636-sketch** [Bitcoin-ABC/ElectrumABC#287]
# Description

# Traceback
```
Traceback (most recent call last):
  File "electrumabc_gui\qt\main_window.py", line 1132, in timer_actions
  File "electrumabc_gui\qt\main_window.py", line 1325, in _update_wallet
  File "electrumabc_gui\qt\util.py", line 1471, in wrapper
  File "electrumabc_gui\qt\util.py", line 1406, in invoke
  File "electrumabc_gui\qt\util.py", line 1283, in invoke
  File "electrumabc_gui\qt\util.py", line 1298, in _invoke
  File "electrumabc_gui\qt\util.py", line 1336, in _doIt
  File "electrumabc_gui\qt\util.py", line 1425, in _call_func_for_all
  File "electrumabc_gui\qt\main_window.py", line 1337, in update_tabs
  File "electrumabc_gui\qt\main_window.py", line 2332, in update_completions
  File "electrumabc_gui\qt\main_window.py", line 2326, in get_contact_payto
AssertionError

```

# System information

- Electrum ABC version: 5.2.2
- Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:24:45) [MSC v.1929 32 bit (Intel)]
- Operating system: Windows-10-10.0.22000-SP0
- Wallet type: imported_privkey
- Locale: de_DE

**Comment by PiRK** [comment]
My guess would be that this is related to the removal of CashAccounts in #249, but I'm not sure what triggered the error exactly.

Are the CashAccounts saved in the config file somehow? Or did an unofficial plugin trigger this ?
